-- Outstanding debts
-- if OWED is negative, then the OTHER_USER owes :userId (-1 * OWED)
SELECT DECODE(DS.HORSE_ID, U.USER_ID, DS.BACKER_ID, DS.HORSE_ID) AS OTHER_USER,
       DECODE(DS.HORSE_ID, U.USER_ID, DS.OWED - DS.PAYED, DS.PAYED - DS.OWED) AS OWED
FROM V$_DEBT_STATUS DS,USERS U
WHERE (DS.HORSE_ID = U.USER_ID OR DS.BACKER_ID = U.USER_ID)
AND U.USER_ID = :userId
